name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  documentation:
    uses: awesomeprojectsss/securedelivery-main/.github/workflows/repository-docs.yml@main
